# Project: MetNewton
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = bgidemo.o $(RES)
LINKOBJ  = bgidemo.o $(RES)
LIBS =  -L"C:/Users/rmendonca/Documents/Trabalho/C++/Dev Portable/App/devcpp/lib" -lbgi -lgdi32 -lcomdlg32 -luuid -loleaut32 -lole32 
INCS =  -I"C:/Users/rmendonca/Documents/Trabalho/C++/Dev Portable/App/devcpp/include" 
CXXINCS =  -I"C:/Users/rmendonca/Documents/Trabalho/C++/Dev Portable/App/devcpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Users/rmendonca/Documents/Trabalho/C++/Dev Portable/App/devcpp/include/c++/3.4.2/backward"  -I"C:/Users/rmendonca/Documents/Trabalho/C++/Dev Portable/App/devcpp/include/c++/3.4.2/mingw32"  -I"C:/Users/rmendonca/Documents/Trabalho/C++/Dev Portable/App/devcpp/include/c++/3.4.2"  -I"C:/Users/rmendonca/Documents/Trabalho/C++/Dev Portable/App/devcpp/include" 
BIN  = MetNewton.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before MetNewton.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "MetNewton.exe" $(LIBS)

bgidemo.o: bgidemo.cpp
	$(CPP) -c bgidemo.cpp -o bgidemo.o $(CXXFLAGS)
