# Project: Matriz3D
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = dllmain.o $(RES)
LINKOBJ  = dllmain.o $(RES)
LIBS =  -L"C:/Users/rmendonca/Documents/Trabalho/C++/Dev Portable/App/devcpp/lib" --no-export-all-symbols --add-stdcall-alias 
INCS =  -I"C:/Users/rmendonca/Documents/Trabalho/C++/Dev Portable/App/devcpp/include" 
CXXINCS =  -I"C:/Users/rmendonca/Documents/Trabalho/C++/Dev Portable/App/devcpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Users/rmendonca/Documents/Trabalho/C++/Dev Portable/App/devcpp/include/c++/3.4.2/backward"  -I"C:/Users/rmendonca/Documents/Trabalho/C++/Dev Portable/App/devcpp/include/c++/3.4.2/mingw32"  -I"C:/Users/rmendonca/Documents/Trabalho/C++/Dev Portable/App/devcpp/include/c++/3.4.2"  -I"C:/Users/rmendonca/Documents/Trabalho/C++/Dev Portable/App/devcpp/include" 
BIN  = Matriz3D.dll
CXXFLAGS = $(CXXINCS) -DBUILDING_DLL=1 
CFLAGS = $(INCS) -DBUILDING_DLL=1 
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Matriz3D.dll all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

DLLWRAP=dllwrap.exe
DEFFILE=libMatriz3D.def
STATICLIB=libMatriz3D.a

$(BIN): $(LINKOBJ)
	$(DLLWRAP) --output-def $(DEFFILE) --driver-name c++ --implib $(STATICLIB) $(LINKOBJ) $(LIBS) -o $(BIN)

dllmain.o: dllmain.cpp
	$(CPP) -c dllmain.cpp -o dllmain.o $(CXXFLAGS)
