// Class automatically generated by Dev-C++ New Class wizard

#ifndef GRAFICOS_H
#define GRAFICOS_H

/*
 * No description
 */
class Graficos
{
	public:
    //Propriedades
        int nEscala;
        int nXTela;
        int nYTela;
        int nRed;
        int nGreen;
        int nBlue;
        
        int nXAnt;
        int nYAnt;
	// Construtor
		Graficos();
	// class destructor
		~Graficos();
		
	// Metodos
		void DesenhaPonto (double,double);
        void DesenhaLinha (double,double,double,double);
        void DesenhaLinha (double,double);
        void DesenhaEscala (void);
        void CriarTela(void);
    private:
    //Propriedades
        int nXCentro;
        int nYCentro;
    // Metodos
        double PixelToCode (int, char);
        int CodeToPixel (double, char);
};

#endif // GRAFICOS_H
